version: '3'

services:
  django:
    build: ./streetparkingspotreservation
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./streetparkingspotreservation:/app/streetparkingspotreservation
    ports:
      - "8000:8000"

