# Generated by Django 2.1.5 on 2019-02-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20190203_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspots',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
