# Generated by Django 2.1.5 on 2019-02-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190203_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='reservation_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservations',
            name='reservation_ends',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='reservations',
            name='reservation_starts',
            field=models.DateTimeField(default=None),
        ),
    ]
